name: Build Go Binaries

on: [push, pull_request]

jobs:
  build-matrix:
    name: Build ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        name:
            - armhf-linux
            - aarch64-linux
            - x86_64-linux-dbg
            - x86_64-macos
            - x86_64-win
            - i686-win
            - i686-linux
        include:
          - name: armhf-linux
            host: arm-linux-gnueabihf
            runs-on: ubuntu-latest
            goos: linux
            goarch: arm32
          - name: aarch64-linux
            host: aarch64-linux-gnu
            runs-on: ubuntu-latest
            goos: linux
            goarch: arm64
          - name: x86_64-linux-dbg
            host: x86_64-pc-linux-gnu
            runs-on: ubuntu-latest
            goos: linux
            goarch: amd64
          - name: i686-linux
            host: i686-pc-linux-gnu
            runs-on: ubuntu-latest
            goos: linux
            goarch: 386
          - name: x86_64-macos
            host: x86_64-apple-darwin14
            runs-on: darwin-latest
            goos: darwin
            goarch: amd64
          - name: x86_64-win
            host: x86_64-w64-mingw32
            runs-on: windows-latest
            goos: windows
            goarch: amd64
          - name: i686-win
            host: i686-w64-mingw32
            runs-on: windows-latest
            goos: windows
            goarch: 386

    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3

    - name: "Build binary"
      run: ./build --host=${{ matrix.host }}
